[package]
name = "nanostring"
version = "0.1.0"
edition = "2021"
authors = ["Raphael Peters <rappet@rappet.de>"]
license = "MIT"
description = "16 byte long string types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
